// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToeicCentre_Management.Data;

#nullable disable

namespace ToeicCentre_Management.Migrations
{
    [DbContext(typeof(TOIECContext))]
    [Migration("20250629173945_AddCascade")]
    partial class AddCascade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChudetlTailieuhoctap", b =>
                {
                    b.Property<int>("MaChuDeTl")
                        .HasColumnType("int");

                    b.Property<int>("MaTl")
                        .HasColumnType("int");

                    b.HasKey("MaChuDeTl", "MaTl");

                    b.ToTable("ChudetlTailieuhoctap");
                });

            modelBuilder.Entity("TailieuChude", b =>
                {
                    b.Property<int>("MaTl")
                        .HasColumnType("int")
                        .HasColumnName("MaTL");

                    b.Property<int>("MaChuDeTl")
                        .HasColumnType("int")
                        .HasColumnName("MaChuDeTL");

                    b.HasKey("MaTl", "MaChuDeTl");

                    b.HasIndex("MaChuDeTl");

                    b.ToTable("TAILIEU_CHUDE", (string)null);
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Baithi", b =>
                {
                    b.Property<int>("MaBt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaBT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBt"));

                    b.Property<DateOnly?>("NgayLap")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayThi")
                        .HasColumnType("date");

                    b.Property<string>("TenBaiThi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TglamBai")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("TGLamBai")
                        .IsFixedLength();

                    b.Property<string>("TongDiem")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.HasKey("MaBt");

                    b.ToTable("BAITHI");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Baiviet", b =>
                {
                    b.Property<int>("MaBv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaBV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBv"));

                    b.Property<int?>("MaDd")
                        .HasColumnType("int")
                        .HasColumnName("MaDD");

                    b.Property<int?>("MaNguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenBV");

                    b.HasKey("MaBv");

                    b.HasIndex("MaDd");

                    b.HasIndex("MaNguoiTao");

                    b.ToTable("BAIVIET");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Bienbanthithu", b =>
                {
                    b.Property<int>("IdBienBanThiThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_BienBanThiThu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBienBanThiThu"));

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DotThiThu")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("GiamThiCoiThi1")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("GiamThiCoiThi2")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("IdThiThu")
                        .HasColumnType("int")
                        .HasColumnName("id_ThiThu");

                    b.HasKey("IdBienBanThiThu");

                    b.HasIndex("IdThiThu");

                    b.ToTable("BIENBANTHITHU");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Cauhoi", b =>
                {
                    b.Property<int>("MaCh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCh"));

                    b.Property<string>("GiaiThichDa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GiaiThichDA");

                    b.Property<int?>("IdGiaoVienTaoCh")
                        .HasColumnType("int")
                        .HasColumnName("ID_GiaoVienTaoCH");

                    b.Property<int?>("IdNguoiDuyetCh")
                        .HasColumnType("int")
                        .HasColumnName("ID_NguoiDuyetCH");

                    b.Property<int?>("MaNhomCh")
                        .HasColumnType("int")
                        .HasColumnName("MaNhomCH");

                    b.Property<int?>("MaTtCh")
                        .HasColumnType("int")
                        .HasColumnName("MaTT_CH");

                    b.Property<string>("NdCauHoi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ND_CauHoi");

                    b.Property<DateOnly?>("NgayCapNhatCh")
                        .HasColumnType("date")
                        .HasColumnName("NgayCapNhatCH");

                    b.Property<DateOnly?>("NgayDuyetCh")
                        .HasColumnType("date")
                        .HasColumnName("NgayDuyetCH");

                    b.Property<DateOnly?>("NgayTaoCh")
                        .HasColumnType("date")
                        .HasColumnName("NgayTaoCH");

                    b.Property<string>("PathAudioRieng")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Path_AudioRieng");

                    b.Property<string>("PathHinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Path_HinhAnh");

                    b.Property<int?>("SttTrongNhom")
                        .HasColumnType("int")
                        .HasColumnName("STT_TrongNhom");

                    b.HasKey("MaCh");

                    b.HasIndex("IdGiaoVienTaoCh");

                    b.HasIndex("IdNguoiDuyetCh");

                    b.HasIndex("MaNhomCh");

                    b.HasIndex("MaTtCh");

                    b.ToTable("CAUHOI");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Cauhoibaitap", b =>
                {
                    b.Property<int>("IdBaiTap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_BaiTap");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaiTap"));

                    b.Property<int>("IdPhieuBaiTap")
                        .HasColumnType("int")
                        .HasColumnName("id_PhieuBaiTap");

                    b.Property<int?>("MaCh")
                        .HasColumnType("int")
                        .HasColumnName("MaCH");

                    b.HasKey("IdBaiTap");

                    b.HasIndex("IdPhieuBaiTap");

                    b.HasIndex("MaCh");

                    b.ToTable("CAUHOIBAITAP");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.CauhoitrongDethi", b =>
                {
                    b.Property<int>("MaDeThi")
                        .HasColumnType("int");

                    b.Property<int>("MaCh")
                        .HasColumnType("int")
                        .HasColumnName("MaCH");

                    b.Property<int?>("SttChTrongDe")
                        .HasColumnType("int")
                        .HasColumnName("STT_CH_TrongDe");

                    b.HasKey("MaDeThi", "MaCh");

                    b.HasIndex("MaCh");

                    b.ToTable("CAUHOITRONG DETHI");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Cautrucdethi", b =>
                {
                    b.Property<int>("MaDeThi")
                        .HasColumnType("int");

                    b.Property<int>("MaPt")
                        .HasColumnType("int")
                        .HasColumnName("MaPT");

                    b.Property<int?>("MaDoKhoPart")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongCau")
                        .HasColumnType("int");

                    b.HasKey("MaDeThi", "MaPt");

                    b.HasIndex("MaDoKhoPart");

                    b.HasIndex("MaPt");

                    b.ToTable("CAUTRUCDETHI");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Chitietbaithi", b =>
                {
                    b.Property<int>("MaBt")
                        .HasColumnType("int")
                        .HasColumnName("MaBT");

                    b.Property<int>("MaSv")
                        .HasColumnType("int")
                        .HasColumnName("MaSV");

                    b.Property<int?>("DiemSo")
                        .HasColumnType("int");

                    b.Property<string>("PhanThi")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("SoCauDung")
                        .HasColumnType("int");

                    b.HasKey("MaBt", "MaSv");

                    b.HasIndex("MaSv");

                    b.ToTable("CHITIETBAITHI");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Chudetl", b =>
                {
                    b.Property<int>("MaChuDeTl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaChuDeTL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuDeTl"));

                    b.Property<string>("MoTaChuDeTl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTaChuDeTL");

                    b.Property<string>("TenChuDeTl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TenChuDeTL");

                    b.HasKey("MaChuDeTl");

                    b.ToTable("CHUDETL");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.DDethi", b =>
                {
                    b.Property<int>("IdDdeThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_DDeThi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDdeThi"));

                    b.Property<int?>("IdDeThi")
                        .HasColumnType("int")
                        .HasColumnName("id_DeThi");

                    b.Property<int?>("MaCh")
                        .HasColumnType("int")
                        .HasColumnName("MaCH");

                    b.HasKey("IdDdeThi");

                    b.HasIndex("IdDeThi");

                    b.HasIndex("MaCh");

                    b.ToTable("D_DETHI");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Dangkyonluyen", b =>
                {
                    b.Property<int>("IdOnLuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_OnLuyen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOnLuyen"));

                    b.Property<int?>("DiemToiecMucTieu")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HinhThucHoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IdLop")
                        .HasColumnType("int")
                        .HasColumnName("id_Lop");

                    b.Property<int?>("MaSv")
                        .HasColumnType("int")
                        .HasColumnName("MaSV");

                    b.Property<string>("TrinhDoHienTai")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("IdOnLuyen");

                    b.HasIndex("IdLop");

                    b.HasIndex("MaSv");

                    b.ToTable("DANGKYONLUYEN");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Dangkythithu", b =>
                {
                    b.Property<int>("IdThiThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ThiThu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThiThu"));

                    b.Property<string>("CaThi")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DotThiThu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IdDeThi")
                        .HasColumnType("int")
                        .HasColumnName("id_DeThi");

                    b.Property<int?>("MaLsdTl")
                        .HasColumnType("int")
                        .HasColumnName("MaLSD_TL");

                    b.Property<int?>("MaSv")
                        .HasColumnType("int")
                        .HasColumnName("MaSV");

                    b.Property<DateOnly?>("NgayThiThu")
                        .HasColumnType("date");

                    b.HasKey("IdThiThu");

                    b.HasIndex("IdDeThi");

                    b.HasIndex("MaLsdTl");

                    b.HasIndex("MaSv");

                    b.ToTable("DANGKYTHITHU");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Dapan", b =>
                {
                    b.Property<int?>("MaDa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("MaDa"));

                    b.Property<string>("KyHieuDa")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("KyHieuDA")
                        .IsFixedLength();

                    b.Property<bool?>("LaDapAnDung")
                        .HasColumnType("bit");

                    b.Property<int?>("MaCh")
                        .HasColumnType("int")
                        .HasColumnName("MaCH");

                    b.Property<string>("NdDapAn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ND_DapAn");

                    b.HasKey("MaDa");

                    b.HasIndex("MaCh");

                    b.ToTable("DAPAN");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Dethi", b =>
                {
                    b.Property<int>("IdDeThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_DeThi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDeThi"));

                    b.Property<string>("HinhThuc")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LoaiDde")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("ThoiGian")
                        .HasColumnType("int");

                    b.HasKey("IdDeThi");

                    b.ToTable("DETHI");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Dethidatao", b =>
                {
                    b.Property<int>("MaDeThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDeThi"));

                    b.Property<bool?>("ChoPhepLamLai")
                        .HasColumnType("bit");

                    b.Property<string>("ChoPhepXemDapAn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DoKhoTongThe")
                        .HasColumnType("int");

                    b.Property<int?>("IdGiaoVienTaoDe")
                        .HasColumnType("int")
                        .HasColumnName("ID_GiaoVienTaoDe");

                    b.Property<int?>("IdSinhVienTaoDe")
                        .HasColumnType("int")
                        .HasColumnName("ID_SinhVienTaoDe");

                    b.Property<int?>("MaLoaiDe")
                        .HasColumnType("int");

                    b.Property<int?>("MaTrangThaiDeThi")
                        .HasColumnType("int");

                    b.Property<string>("MoTaDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NamThamKhao")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTaoDe")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayXuatBan")
                        .HasColumnType("datetime");

                    b.Property<string>("NguonGocThamKhao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SoLanLamLaiMax")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDeThi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ThoiGianLamBaiPhut")
                        .HasColumnType("int")
                        .HasColumnName("ThoiGianLamBai_Phut");

                    b.HasKey("MaDeThi");

                    b.HasIndex("IdGiaoVienTaoDe");

                    b.HasIndex("IdSinhVienTaoDe");

                    b.HasIndex("MaLoaiDe");

                    b.HasIndex("MaTrangThaiDeThi");

                    b.ToTable("DETHIDATAO");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Diemthi", b =>
                {
                    b.Property<int>("IdDiemThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_DiemThi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiemThi"));

                    b.Property<string>("Bac")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int?>("DiemPart1")
                        .HasColumnType("int");

                    b.Property<int?>("DiemPart2")
                        .HasColumnType("int");

                    b.Property<int?>("DiemPart3")
                        .HasColumnType("int");

                    b.Property<int?>("DiemPart4")
                        .HasColumnType("int");

                    b.Property<int?>("DiemPart5")
                        .HasColumnType("int");

                    b.Property<int?>("DiemPart6")
                        .HasColumnType("int");

                    b.Property<int?>("DiemPart7")
                        .HasColumnType("int");

                    b.Property<int?>("IdThiThu")
                        .HasColumnType("int")
                        .HasColumnName("id_ThiThu");

                    b.Property<int?>("MaSv")
                        .HasColumnType("int")
                        .HasColumnName("MaSV");

                    b.Property<int?>("TongDiem")
                        .HasColumnType("int");

                    b.HasKey("IdDiemThi");

                    b.HasIndex("IdThiThu");

                    b.HasIndex("MaSv");

                    b.ToTable("DIEMTHI");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Diendan", b =>
                {
                    b.Property<int>("MaDd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDd"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HanhDong")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("MaDdn")
                        .HasColumnType("int")
                        .HasColumnName("MaDDN");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("SoBaiViet")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("MaDd");

                    b.HasIndex("MaDdn");

                    b.ToTable("DIENDAN");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Dondenghitaodd", b =>
                {
                    b.Property<int>("MaDdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDdn"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("DonVi")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("HinhThucTrienKhai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoiIchKyVong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("NgayVietDon")
                        .HasColumnType("date");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDienDanDeXuat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenNguoiDn")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("TenNguoiDN");

                    b.HasKey("MaDdn");

                    b.ToTable("DONDENGHITAODD");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Donkhieunai", b =>
                {
                    b.Property<int>("MaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDon"));

                    b.Property<int?>("CauSo")
                        .HasColumnType("int");

                    b.Property<string>("DeNghiXemXet")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HinhThucCauHoi")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("MaBt")
                        .HasColumnType("int")
                        .HasColumnName("MaBT");

                    b.Property<int?>("MaSv")
                        .HasColumnType("int")
                        .HasColumnName("MaSV");

                    b.Property<string>("MoTaSaiSot")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiLap")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("MaDon");

                    b.HasIndex("MaBt");

                    b.HasIndex("MaSv");

                    b.ToTable("DONKHIEUNAI");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Giaovien", b =>
                {
                    b.Property<int>("MaGv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaGV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGv"));

                    b.Property<string>("CapBac")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MatKhauGv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MatKhauGV");

                    b.Property<decimal?>("Sdt")
                        .HasColumnType("numeric(10, 0)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenDangNhapGv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TenDangNhapGV");

                    b.Property<string>("TenGiaoVien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaGv");

                    b.ToTable("GIAOVIEN");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.GiaovienDiendan", b =>
                {
                    b.Property<int>("MaDd")
                        .HasColumnType("int")
                        .HasColumnName("MaDD");

                    b.Property<int>("MaGv")
                        .HasColumnType("int")
                        .HasColumnName("MaGV");

                    b.Property<DateTime?>("TgTao")
                        .HasColumnType("datetime")
                        .HasColumnName("TG_Tao");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("MaDd", "MaGv");

                    b.HasIndex("MaGv");

                    b.ToTable("GIAOVIEN_DIENDAN");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Kiemduyetvien", b =>
                {
                    b.Property<int>("MaKdv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKDV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKdv"));

                    b.Property<string>("EmailKdv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EmailKDV");

                    b.Property<string>("HoTenKdv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("HoTenKDV");

                    b.Property<string>("MatKhauKdv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MatKhauKDV");

                    b.Property<string>("TenDangNhapKdv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenDangNhapKDV");

                    b.HasKey("MaKdv");

                    b.ToTable("KIEMDUYETVIEN");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Kynang", b =>
                {
                    b.Property<int>("MaKn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKn"));

                    b.Property<string>("TenKn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenKN");

                    b.HasKey("MaKn");

                    b.ToTable("KYNANG");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Lichhoc", b =>
                {
                    b.Property<int>("LichId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LichID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LichId"));

                    b.Property<int?>("LopId")
                        .HasColumnType("int")
                        .HasColumnName("LopID");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime");

                    b.HasKey("LichId");

                    b.ToTable("LICHHOC");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Lichsuduyetch", b =>
                {
                    b.Property<int>("MaLsd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaLSD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLsd"));

                    b.Property<string>("GhiChuDuyet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiCHuDuyet");

                    b.Property<int?>("IdNguoiDuyetLs")
                        .HasColumnType("int")
                        .HasColumnName("ID_NguoiDuyetLS");

                    b.Property<int?>("MaCh")
                        .HasColumnType("int")
                        .HasColumnName("MaCH");

                    b.Property<int?>("MaTtSau")
                        .HasColumnType("int")
                        .HasColumnName("MaTT_Sau");

                    b.Property<int?>("MaTtTruoc")
                        .HasColumnType("int")
                        .HasColumnName("MaTT_Truoc");

                    b.Property<DateTime?>("ThoiDiemDuyet")
                        .HasColumnType("datetime");

                    b.HasKey("MaLsd");

                    b.HasIndex("IdNguoiDuyetLs");

                    b.HasIndex("MaCh");

                    b.HasIndex("MaTtSau");

                    b.HasIndex("MaTtTruoc");

                    b.ToTable("LICHSUDUYETCH");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Lichsuduyettl", b =>
                {
                    b.Property<int>("MaLsdTl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaLSD_TL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLsdTl"));

                    b.Property<string>("GhiChuDuyetTl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChuDuyetTL");

                    b.Property<int?>("IdNguoiDuyetLsTl")
                        .HasColumnType("int")
                        .HasColumnName("ID_NguoiDuyetLS_TL");

                    b.Property<int?>("MaTl")
                        .HasColumnType("int")
                        .HasColumnName("MaTL");

                    b.Property<int?>("MaTtMoiTl")
                        .HasColumnType("int")
                        .HasColumnName("MaTT_Moi_TL");

                    b.Property<int?>("MaTtTruocTl")
                        .HasColumnType("int")
                        .HasColumnName("MaTT_Truoc_TL");

                    b.Property<DateTime?>("ThoiDiemDuyetTl")
                        .HasColumnType("datetime")
                        .HasColumnName("ThoiDiemDuyetTL");

                    b.HasKey("MaLsdTl");

                    b.HasIndex("IdNguoiDuyetLsTl");

                    b.HasIndex("MaTl");

                    b.HasIndex("MaTtMoiTl");

                    b.HasIndex("MaTtTruocTl");

                    b.ToTable("LICHSUDUYETTL");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Lichthitoiec", b =>
                {
                    b.Property<int>("LichThiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LichThiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LichThiId"));

                    b.Property<string>("DiaDiemThi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("LichThiId");

                    b.ToTable("LICHTHITOIEC");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Loaidethi", b =>
                {
                    b.Property<int>("MaLoaiDe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiDe"));

                    b.Property<string>("TenLoaiDe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiDe");

                    b.ToTable("LOAIDETHI");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Loaitailieu", b =>
                {
                    b.Property<int>("MaLoaiTl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaLoaiTL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiTl"));

                    b.Property<string>("MoTaLoaiTl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTaLoaiTL");

                    b.Property<string>("TenLoaiTl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenLoaiTL");

                    b.HasKey("MaLoaiTl");

                    b.ToTable("LOAITAILIEU");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Lop", b =>
                {
                    b.Property<int>("IdLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Lop");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLop"));

                    b.Property<int?>("MaGv")
                        .HasColumnType("int")
                        .HasColumnName("MaGV");

                    b.Property<string>("TenLop")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateOnly?>("ThangBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ThangKetThuc")
                        .HasColumnType("date");

                    b.HasKey("IdLop");

                    b.HasIndex("MaGv");

                    b.ToTable("LOP");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Mucdokho", b =>
                {
                    b.Property<int>("MaMdk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaMDK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMdk"));

                    b.Property<string>("TenMdk")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenMDK");

                    b.HasKey("MaMdk");

                    b.ToTable("MUCDOKHO");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Nhomch", b =>
                {
                    b.Property<int>("MaNhomCh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNhomCH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhomCh"));

                    b.Property<int?>("IdGiaoVienTao")
                        .HasColumnType("int")
                        .HasColumnName("ID_GiaoVienTao");

                    b.Property<string>("KyHieuNhomCh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KyHieu_NhomCh");

                    b.Property<int?>("MaPt")
                        .HasColumnType("int")
                        .HasColumnName("MaPT");

                    b.Property<string>("NdDoanVan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ND_DoanVan");

                    b.Property<string>("NdHoiThoai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ND_HoiThoai");

                    b.Property<DateOnly?>("NgayTaoNhom")
                        .HasColumnType("date");

                    b.Property<string>("PathAudioNhom")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Path_AudioNhom");

                    b.HasKey("MaNhomCh")
                        .HasName("PK_NHOMCH");

                    b.HasIndex("IdGiaoVienTao");

                    b.HasIndex("MaPt");

                    b.ToTable("NHOMCH");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Phanloaich", b =>
                {
                    b.Property<int>("MaCh")
                        .HasColumnType("int")
                        .HasColumnName("MaCH");

                    b.Property<int>("MaPt")
                        .HasColumnType("int")
                        .HasColumnName("MaPT");

                    b.Property<int>("MaKn")
                        .HasColumnType("int")
                        .HasColumnName("MaKN");

                    b.Property<int>("MaMdk")
                        .HasColumnType("int")
                        .HasColumnName("MaMDK");

                    b.HasKey("MaCh", "MaPt");

                    b.HasIndex("MaKn");

                    b.HasIndex("MaMdk");

                    b.HasIndex("MaPt");

                    b.ToTable("PHANLOAICH");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Phanloaitl", b =>
                {
                    b.Property<int>("MaPl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaPL");

                    b.Property<int?>("MaKn")
                        .HasColumnType("int")
                        .HasColumnName("MaKN");

                    b.Property<int?>("MaPt")
                        .HasColumnType("int")
                        .HasColumnName("MaPT");

                    b.HasKey("MaPl");

                    b.HasIndex("MaKn");

                    b.ToTable("PHANLOAITL");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Phanthi", b =>
                {
                    b.Property<int>("MaPt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaPT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPt"));

                    b.Property<int?>("MaKn")
                        .HasColumnType("int")
                        .HasColumnName("MaKN");

                    b.Property<string>("TenPt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenPT");

                    b.HasKey("MaPt");

                    b.HasIndex("MaKn");

                    b.ToTable("PHANTHI");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Phieubaitaponluyen", b =>
                {
                    b.Property<int>("IdPhieuBaiTap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_PhieuBaiTap");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPhieuBaiTap"));

                    b.Property<string>("DangCauHoi")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("DiemSo")
                        .HasColumnType("int");

                    b.Property<string>("Lop")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("MaSv")
                        .HasColumnType("int")
                        .HasColumnName("MaSV");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ThoiGianGiao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ThoiGianNop")
                        .HasColumnType("datetime");

                    b.HasKey("IdPhieuBaiTap");

                    b.HasIndex("MaSv");

                    b.ToTable("PHIEUBAITAPONLUYEN");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Phieudangkytoiec", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieu"));

                    b.Property<decimal>("Cccd")
                        .HasColumnType("numeric(12, 0)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChiLienHe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("GioThi")
                        .HasColumnType("datetime");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoVaTen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("LePhiThi")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("NgayDangKy")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayGioDangKy")
                        .HasColumnType("datetime");

                    b.Property<DateOnly?>("NgayKiemTraKetQua")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("NoiCongTac")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("SoDienThoai")
                        .HasColumnType("numeric(10, 0)");

                    b.Property<string>("TenDonVi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("MaPhieu");

                    b.ToTable("PHIEUDANGKYTOIEC");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Sinhvien", b =>
                {
                    b.Property<int>("MaSv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSv"));

                    b.Property<decimal?>("Cccd")
                        .HasColumnType("numeric(12, 0)")
                        .HasColumnName("CCCD");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTenSv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("HoTenSV");

                    b.Property<string>("Lop")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhauSv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MatKhauSV");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("TenDangNhapSv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaSv");

                    b.ToTable("SINHVIEN");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Tailieuhoctap", b =>
                {
                    b.Property<int>("MaTl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTl"));

                    b.Property<int?>("IdNguoiDuyetTl")
                        .HasColumnType("int")
                        .HasColumnName("ID_NguoiDuyetTL");

                    b.Property<int?>("IdNguoiTaiLen")
                        .HasColumnType("int")
                        .HasColumnName("ID_NguoiTaiLen");

                    b.Property<int?>("MaLoaiTl")
                        .HasColumnType("int")
                        .HasColumnName("MaLoaiTL");

                    b.Property<int?>("MaTtTl")
                        .HasColumnType("int")
                        .HasColumnName("MaTT_TL");

                    b.Property<string>("MoTaNganTl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTaNganTL");

                    b.Property<DateTime?>("NgayCapNhatTlCuoi")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayCapNhatTL_Cuoi");

                    b.Property<DateTime?>("NgayDuyetTl")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayDuyetTL");

                    b.Property<DateTime?>("NgayTaiLenTl")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTaiLenTL");

                    b.Property<string>("NoiDungVanBan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathFileTl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Path_FileTL");

                    b.Property<string>("TieuDeTl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TieuDeTL");

                    b.Property<string>("UrlNgoaiTl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("URL_NgoaiTL");

                    b.HasKey("MaTl");

                    b.HasIndex("IdNguoiDuyetTl");

                    b.HasIndex("IdNguoiTaiLen");

                    b.HasIndex("MaLoaiTl");

                    b.HasIndex("MaTtTl");

                    b.ToTable("TAILIEUHOCTAP");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Thamgium", b =>
                {
                    b.Property<int>("MaDd")
                        .HasColumnType("int")
                        .HasColumnName("MaDD");

                    b.Property<int>("MaSv")
                        .HasColumnType("int")
                        .HasColumnName("MaSV");

                    b.Property<DateTime?>("TgthamGia")
                        .HasColumnType("datetime")
                        .HasColumnName("TGThamGia");

                    b.HasKey("MaDd", "MaSv");

                    b.HasIndex("MaSv");

                    b.ToTable("THAMGIA");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Thongkelop", b =>
                {
                    b.Property<int>("IdThongke")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_Thongke");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThongke"));

                    b.Property<string>("DotThiThu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IdLop")
                        .HasColumnType("int")
                        .HasColumnName("id_Lop");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SoTren450")
                        .HasColumnType("int");

                    b.Property<int?>("SoTren600")
                        .HasColumnType("int");

                    b.Property<int?>("TongHocVien")
                        .HasColumnType("int");

                    b.Property<int?>("TrungBinhDiem")
                        .HasColumnType("int");

                    b.HasKey("IdThongke");

                    b.HasIndex("IdLop");

                    b.ToTable("THONGKELOP");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Trangthaich", b =>
                {
                    b.Property<int>("MaTtCh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTT_CH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTtCh"));

                    b.Property<string>("TenTtCh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenTT_CH");

                    b.HasKey("MaTtCh");

                    b.ToTable("TRANGTHAICH");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Trangthaidethi", b =>
                {
                    b.Property<int>("MaTrangThaiDe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTrangThaiDe"));

                    b.Property<string>("TenTrangThaiDe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTrangThaiDe");

                    b.ToTable("TRANGTHAIDETHI");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Trangthaitl", b =>
                {
                    b.Property<int>("MaTtTl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTT_Tl");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTtTl"));

                    b.Property<string>("KyHieuTtTl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KyHieuTT_TL");

                    b.Property<string>("MoTaTtTl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTaTT_TL");

                    b.Property<string>("TenTtTl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenTT_TL");

                    b.HasKey("MaTtTl");

                    b.ToTable("TRANGTHAITL");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.TtLichthitoiec", b =>
                {
                    b.Property<int>("MaTtLichThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTT_LichThi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTtLichThi"));

                    b.Property<DateTime?>("GioBatDauLamBai")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("GioThuTuc")
                        .HasColumnType("datetime");

                    b.Property<int?>("LichThiId")
                        .HasColumnType("int")
                        .HasColumnName("LichThiID");

                    b.Property<string>("LoaiBaiThi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("NgayThi")
                        .HasColumnType("date");

                    b.HasKey("MaTtLichThi");

                    b.ToTable("TT_LICHTHITOIEC");
                });

            modelBuilder.Entity("TailieuChude", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Chudetl", null)
                        .WithMany()
                        .HasForeignKey("MaChuDeTl")
                        .IsRequired()
                        .HasConstraintName("FK_TAILIEU_CHUDE_CHUDETL");

                    b.HasOne("ToeicCentre_Management.Models.Tailieuhoctap", null)
                        .WithMany()
                        .HasForeignKey("MaTl")
                        .IsRequired()
                        .HasConstraintName("FK_TAILIEU_CHUDE_TAILIEUHOCTAP");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Baiviet", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Diendan", "MaDdNavigation")
                        .WithMany("Baiviets")
                        .HasForeignKey("MaDd")
                        .HasConstraintName("FK_BAIVIET_DIENDAN");

                    b.HasOne("ToeicCentre_Management.Models.Giaovien", "MaNguoiTaoNavigation")
                        .WithMany("Baiviets")
                        .HasForeignKey("MaNguoiTao")
                        .HasConstraintName("FK_BAIVIET_GIAOVIEN");

                    b.Navigation("MaDdNavigation");

                    b.Navigation("MaNguoiTaoNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Bienbanthithu", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Dangkythithu", "IdThiThuNavigation")
                        .WithMany("Bienbanthithus")
                        .HasForeignKey("IdThiThu")
                        .HasConstraintName("FK_BIENBANTHITHU_DANGKYTHITHU");

                    b.Navigation("IdThiThuNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Cauhoi", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Giaovien", "IdGiaoVienTaoChNavigation")
                        .WithMany("Cauhois")
                        .HasForeignKey("IdGiaoVienTaoCh")
                        .HasConstraintName("FK_CAUHOI_GIAOVIEN");

                    b.HasOne("ToeicCentre_Management.Models.Kiemduyetvien", "IdNguoiDuyetChNavigation")
                        .WithMany("Cauhois")
                        .HasForeignKey("IdNguoiDuyetCh")
                        .HasConstraintName("FK_CAUHOI_KIEMDUYETVIEN");

                    b.HasOne("ToeicCentre_Management.Models.Nhomch", "MaNhomChNavigation")
                        .WithMany("Cauhois")
                        .HasForeignKey("MaNhomCh")
                        .HasConstraintName("FK_CAUHOI_NHOMCH");

                    b.HasOne("ToeicCentre_Management.Models.Trangthaich", "MaTtChNavigation")
                        .WithMany("Cauhois")
                        .HasForeignKey("MaTtCh")
                        .HasConstraintName("FK_CAUHOI_TRANGTHAICH");

                    b.Navigation("IdGiaoVienTaoChNavigation");

                    b.Navigation("IdNguoiDuyetChNavigation");

                    b.Navigation("MaNhomChNavigation");

                    b.Navigation("MaTtChNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Cauhoibaitap", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Phieubaitaponluyen", "IdPhieuBaiTapNavigation")
                        .WithMany("Cauhoibaitaps")
                        .HasForeignKey("IdPhieuBaiTap")
                        .IsRequired()
                        .HasConstraintName("FK_CAUHOIBAITAP_PHIEUBAITAPONLUYEN");

                    b.HasOne("ToeicCentre_Management.Models.Cauhoi", "MaChNavigation")
                        .WithMany("Cauhoibaitaps")
                        .HasForeignKey("MaCh")
                        .HasConstraintName("FK_CAUHOIBAITAP_CAUHOI");

                    b.Navigation("IdPhieuBaiTapNavigation");

                    b.Navigation("MaChNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.CauhoitrongDethi", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Cauhoi", "MaChNavigation")
                        .WithMany("CauhoitrongDethis")
                        .HasForeignKey("MaCh")
                        .IsRequired()
                        .HasConstraintName("FK_CAUHOITRONG DETHI_CAUHOI");

                    b.HasOne("ToeicCentre_Management.Models.Dethidatao", "MaDeThiNavigation")
                        .WithMany("CauhoitrongDethis")
                        .HasForeignKey("MaDeThi")
                        .IsRequired()
                        .HasConstraintName("FK_CAUHOITRONG DETHI_DETHIDATAO");

                    b.Navigation("MaChNavigation");

                    b.Navigation("MaDeThiNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Cautrucdethi", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Mucdokho", "MaDoKhoPartNavigation")
                        .WithMany("Cautrucdethis")
                        .HasForeignKey("MaDoKhoPart")
                        .HasConstraintName("FK_CAUTRUCDETHI_MUCDOKHO");

                    b.HasOne("ToeicCentre_Management.Models.Phanthi", "MaPtNavigation")
                        .WithMany("Cautrucdethis")
                        .HasForeignKey("MaPt")
                        .IsRequired()
                        .HasConstraintName("FK_CAUTRUCDETHI_PHANTHI");

                    b.Navigation("MaDoKhoPartNavigation");

                    b.Navigation("MaPtNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Chitietbaithi", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Baithi", "MaBtNavigation")
                        .WithMany("Chitietbaithis")
                        .HasForeignKey("MaBt")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETBAITHI_BAITHI");

                    b.HasOne("ToeicCentre_Management.Models.Sinhvien", "MaSvNavigation")
                        .WithMany("Chitietbaithis")
                        .HasForeignKey("MaSv")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETBAITHI_SINHVIEN");

                    b.Navigation("MaBtNavigation");

                    b.Navigation("MaSvNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.DDethi", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Dethi", "IdDeThiNavigation")
                        .WithMany("DDethis")
                        .HasForeignKey("IdDeThi")
                        .HasConstraintName("FK_D_DETHI_DETHI");

                    b.HasOne("ToeicCentre_Management.Models.Cauhoi", "MaChNavigation")
                        .WithMany("DDethis")
                        .HasForeignKey("MaCh")
                        .HasConstraintName("FK_D_DETHI_CAUHOI");

                    b.Navigation("IdDeThiNavigation");

                    b.Navigation("MaChNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Dangkyonluyen", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Lop", "IdLopNavigation")
                        .WithMany("Dangkyonluyens")
                        .HasForeignKey("IdLop")
                        .HasConstraintName("FK_DANGKYONLUYEN_LOP");

                    b.HasOne("ToeicCentre_Management.Models.Sinhvien", "MaSvNavigation")
                        .WithMany("Dangkyonluyens")
                        .HasForeignKey("MaSv")
                        .HasConstraintName("FK_DANGKYONLUYEN_SINHVIEN");

                    b.Navigation("IdLopNavigation");

                    b.Navigation("MaSvNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Dangkythithu", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Dethi", "IdDeThiNavigation")
                        .WithMany("Dangkythithus")
                        .HasForeignKey("IdDeThi")
                        .HasConstraintName("FK_DANGKYTHITHU_DETHI");

                    b.HasOne("ToeicCentre_Management.Models.Lichsuduyettl", "MaLsdTlNavigation")
                        .WithMany("Dangkythithus")
                        .HasForeignKey("MaLsdTl")
                        .HasConstraintName("FK_DANGKYTHITHU_LICHSUDUYETTL");

                    b.HasOne("ToeicCentre_Management.Models.Sinhvien", "MaSvNavigation")
                        .WithMany("Dangkythithus")
                        .HasForeignKey("MaSv")
                        .HasConstraintName("FK_DANGKYTHITHU_SINHVIEN");

                    b.Navigation("IdDeThiNavigation");

                    b.Navigation("MaLsdTlNavigation");

                    b.Navigation("MaSvNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Dapan", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Cauhoi", "MaChNavigation")
                        .WithMany("Dapans")
                        .HasForeignKey("MaCh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_DAPAN_CAUHOI");

                    b.Navigation("MaChNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Dethidatao", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Giaovien", "IdGiaoVienTaoDeNavigation")
                        .WithMany("Dethidataos")
                        .HasForeignKey("IdGiaoVienTaoDe")
                        .HasConstraintName("FK_DETHIDATAO_GIAOVIEN");

                    b.HasOne("ToeicCentre_Management.Models.Sinhvien", "IdSinhVienTaoDeNavigation")
                        .WithMany("Dethidataos")
                        .HasForeignKey("IdSinhVienTaoDe")
                        .HasConstraintName("FK_DETHIDATAO_SINHVIEN");

                    b.HasOne("ToeicCentre_Management.Models.Loaidethi", "MaLoaiDeNavigation")
                        .WithMany("Dethidataos")
                        .HasForeignKey("MaLoaiDe")
                        .HasConstraintName("FK_DETHIDATAO_LOAIDETHI");

                    b.HasOne("ToeicCentre_Management.Models.Trangthaidethi", "MaTrangThaiDeThiNavigation")
                        .WithMany("Dethidataos")
                        .HasForeignKey("MaTrangThaiDeThi")
                        .HasConstraintName("FK_DETHIDATAO_TRANGTHAIDETHI");

                    b.Navigation("IdGiaoVienTaoDeNavigation");

                    b.Navigation("IdSinhVienTaoDeNavigation");

                    b.Navigation("MaLoaiDeNavigation");

                    b.Navigation("MaTrangThaiDeThiNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Diemthi", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Dangkythithu", "IdThiThuNavigation")
                        .WithMany("Diemthis")
                        .HasForeignKey("IdThiThu")
                        .HasConstraintName("FK_DIEMTHI_DANGKYTHITHU");

                    b.HasOne("ToeicCentre_Management.Models.Sinhvien", "MaSvNavigation")
                        .WithMany("Diemthis")
                        .HasForeignKey("MaSv")
                        .HasConstraintName("FK_DIEMTHI_SINHVIEN");

                    b.Navigation("IdThiThuNavigation");

                    b.Navigation("MaSvNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Diendan", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Dondenghitaodd", "MaDdnNavigation")
                        .WithMany("Diendans")
                        .HasForeignKey("MaDdn")
                        .HasConstraintName("FK_DIENDAN_DONDENGHITAODD");

                    b.Navigation("MaDdnNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Donkhieunai", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Baithi", "MaBtNavigation")
                        .WithMany("Donkhieunais")
                        .HasForeignKey("MaBt")
                        .HasConstraintName("FK_DONKHIEUNAI_BAITHI");

                    b.HasOne("ToeicCentre_Management.Models.Sinhvien", "MaSvNavigation")
                        .WithMany("Donkhieunais")
                        .HasForeignKey("MaSv")
                        .HasConstraintName("FK_DONKHIEUNAI_SINHVIEN");

                    b.Navigation("MaBtNavigation");

                    b.Navigation("MaSvNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.GiaovienDiendan", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Diendan", "MaDdNavigation")
                        .WithMany("GiaovienDiendans")
                        .HasForeignKey("MaDd")
                        .IsRequired()
                        .HasConstraintName("FK_GIAOVIEN_DIENDAN_DIENDAN");

                    b.HasOne("ToeicCentre_Management.Models.Giaovien", "MaGvNavigation")
                        .WithMany("GiaovienDiendans")
                        .HasForeignKey("MaGv")
                        .IsRequired()
                        .HasConstraintName("FK_GIAOVIEN_DIENDAN_GIAOVIEN");

                    b.Navigation("MaDdNavigation");

                    b.Navigation("MaGvNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Lichsuduyetch", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Kiemduyetvien", "IdNguoiDuyetLsNavigation")
                        .WithMany("Lichsuduyetches")
                        .HasForeignKey("IdNguoiDuyetLs")
                        .HasConstraintName("FK_LICHSUDUYETCH_KIEMDUYETVIEN");

                    b.HasOne("ToeicCentre_Management.Models.Cauhoi", "MaChNavigation")
                        .WithMany("Lichsuduyetches")
                        .HasForeignKey("MaCh")
                        .HasConstraintName("FK_LICHSUDUYETCH_CAUHOI");

                    b.HasOne("ToeicCentre_Management.Models.Trangthaich", "MaTtSauNavigation")
                        .WithMany("LichsuduyetchMaTtSauNavigations")
                        .HasForeignKey("MaTtSau")
                        .HasConstraintName("FK_LICHSUDUYETCH_TRANGTHAICH1");

                    b.HasOne("ToeicCentre_Management.Models.Trangthaich", "MaTtTruocNavigation")
                        .WithMany("LichsuduyetchMaTtTruocNavigations")
                        .HasForeignKey("MaTtTruoc")
                        .HasConstraintName("FK_LICHSUDUYETCH_TRANGTHAICH");

                    b.Navigation("IdNguoiDuyetLsNavigation");

                    b.Navigation("MaChNavigation");

                    b.Navigation("MaTtSauNavigation");

                    b.Navigation("MaTtTruocNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Lichsuduyettl", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Kiemduyetvien", "IdNguoiDuyetLsTlNavigation")
                        .WithMany("Lichsuduyettls")
                        .HasForeignKey("IdNguoiDuyetLsTl")
                        .HasConstraintName("FK_LICHSUDUYETTL_KIEMDUYETVIEN");

                    b.HasOne("ToeicCentre_Management.Models.Tailieuhoctap", "MaTlNavigation")
                        .WithMany("Lichsuduyettls")
                        .HasForeignKey("MaTl")
                        .HasConstraintName("FK_LICHSUDUYETTL_TAILIEUHOCTAP");

                    b.HasOne("ToeicCentre_Management.Models.Trangthaitl", "MaTtMoiTlNavigation")
                        .WithMany("LichsuduyettlMaTtMoiTlNavigations")
                        .HasForeignKey("MaTtMoiTl")
                        .HasConstraintName("FK_LICHSUDUYETTL_TRANGTHAITL1");

                    b.HasOne("ToeicCentre_Management.Models.Trangthaitl", "MaTtTruocTlNavigation")
                        .WithMany("LichsuduyettlMaTtTruocTlNavigations")
                        .HasForeignKey("MaTtTruocTl")
                        .HasConstraintName("FK_LICHSUDUYETTL_TRANGTHAITL");

                    b.Navigation("IdNguoiDuyetLsTlNavigation");

                    b.Navigation("MaTlNavigation");

                    b.Navigation("MaTtMoiTlNavigation");

                    b.Navigation("MaTtTruocTlNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Lop", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Giaovien", "MaGvNavigation")
                        .WithMany("Lops")
                        .HasForeignKey("MaGv")
                        .HasConstraintName("FK_LOP_GIAOVIEN");

                    b.Navigation("MaGvNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Nhomch", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Giaovien", "IdGiaoVienTaoNavigation")
                        .WithMany("Nhomches")
                        .HasForeignKey("IdGiaoVienTao")
                        .HasConstraintName("FK_NHOMCH_GIAOVIEN");

                    b.HasOne("ToeicCentre_Management.Models.Phanthi", "MaPtNavigation")
                        .WithMany("Nhomches")
                        .HasForeignKey("MaPt")
                        .HasConstraintName("FK_NHOMCH_PHANTHI");

                    b.Navigation("IdGiaoVienTaoNavigation");

                    b.Navigation("MaPtNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Phanloaich", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Cauhoi", "MaChNavigation")
                        .WithMany("Phanloaiches")
                        .HasForeignKey("MaCh")
                        .IsRequired()
                        .HasConstraintName("FK_PHANLOAICH_CAUHOI");

                    b.HasOne("ToeicCentre_Management.Models.Kynang", "MaKnNavigation")
                        .WithMany("Phanloaiches")
                        .HasForeignKey("MaKn")
                        .IsRequired()
                        .HasConstraintName("FK_PHANLOAICH_KYNANG");

                    b.HasOne("ToeicCentre_Management.Models.Mucdokho", "MaMdkNavigation")
                        .WithMany("Phanloaiches")
                        .HasForeignKey("MaMdk")
                        .IsRequired()
                        .HasConstraintName("FK_PHANLOAICH_MUCDOKHO");

                    b.HasOne("ToeicCentre_Management.Models.Phanthi", "MaPtNavigation")
                        .WithMany("Phanloaiches")
                        .HasForeignKey("MaPt")
                        .IsRequired()
                        .HasConstraintName("FK_PHANLOAICH_PHANTHI");

                    b.Navigation("MaChNavigation");

                    b.Navigation("MaKnNavigation");

                    b.Navigation("MaMdkNavigation");

                    b.Navigation("MaPtNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Phanloaitl", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Kynang", "MaKnNavigation")
                        .WithMany("Phanloaitls")
                        .HasForeignKey("MaKn")
                        .HasConstraintName("FK_PHANLOAITL_KYNANG");

                    b.HasOne("ToeicCentre_Management.Models.Phanthi", "MaPlNavigation")
                        .WithOne("Phanloaitl")
                        .HasForeignKey("ToeicCentre_Management.Models.Phanloaitl", "MaPl")
                        .IsRequired()
                        .HasConstraintName("FK_PHANLOAITL_PHANTHI");

                    b.Navigation("MaKnNavigation");

                    b.Navigation("MaPlNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Phanthi", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Kynang", "MaKnNavigation")
                        .WithMany("Phanthis")
                        .HasForeignKey("MaKn")
                        .HasConstraintName("FK_PHANTHI_KYNANG");

                    b.Navigation("MaKnNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Phieubaitaponluyen", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Sinhvien", "MaSvNavigation")
                        .WithMany("Phieubaitaponluyens")
                        .HasForeignKey("MaSv")
                        .HasConstraintName("FK_PHIEUBAITAPONLUYEN_SINHVIEN");

                    b.Navigation("MaSvNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Tailieuhoctap", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Kiemduyetvien", "IdNguoiDuyetTlNavigation")
                        .WithMany("Tailieuhoctaps")
                        .HasForeignKey("IdNguoiDuyetTl")
                        .HasConstraintName("FK_TAILIEUHOCTAP_KIEMDUYETVIEN");

                    b.HasOne("ToeicCentre_Management.Models.Giaovien", "IdNguoiTaiLenNavigation")
                        .WithMany("Tailieuhoctaps")
                        .HasForeignKey("IdNguoiTaiLen")
                        .HasConstraintName("FK_TAILIEUHOCTAP_GIAOVIEN");

                    b.HasOne("ToeicCentre_Management.Models.Loaitailieu", "MaLoaiTlNavigation")
                        .WithMany("Tailieuhoctaps")
                        .HasForeignKey("MaLoaiTl")
                        .HasConstraintName("FK_TAILIEUHOCTAP_LOAITAILIEU");

                    b.HasOne("ToeicCentre_Management.Models.Trangthaitl", "MaTtTlNavigation")
                        .WithMany("Tailieuhoctaps")
                        .HasForeignKey("MaTtTl")
                        .HasConstraintName("FK_TAILIEUHOCTAP_TRANGTHAITL");

                    b.Navigation("IdNguoiDuyetTlNavigation");

                    b.Navigation("IdNguoiTaiLenNavigation");

                    b.Navigation("MaLoaiTlNavigation");

                    b.Navigation("MaTtTlNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Thamgium", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Diendan", "MaDdNavigation")
                        .WithMany("Thamgia")
                        .HasForeignKey("MaDd")
                        .IsRequired()
                        .HasConstraintName("FK_THAMGIA_DIENDAN");

                    b.HasOne("ToeicCentre_Management.Models.Sinhvien", "MaSvNavigation")
                        .WithMany("Thamgia")
                        .HasForeignKey("MaSv")
                        .IsRequired()
                        .HasConstraintName("FK_THAMGIA_SINHVIEN");

                    b.Navigation("MaDdNavigation");

                    b.Navigation("MaSvNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Thongkelop", b =>
                {
                    b.HasOne("ToeicCentre_Management.Models.Lop", "IdLopNavigation")
                        .WithMany("Thongkelops")
                        .HasForeignKey("IdLop")
                        .HasConstraintName("FK_THONGKELOP_LOP");

                    b.Navigation("IdLopNavigation");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Baithi", b =>
                {
                    b.Navigation("Chitietbaithis");

                    b.Navigation("Donkhieunais");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Cauhoi", b =>
                {
                    b.Navigation("Cauhoibaitaps");

                    b.Navigation("CauhoitrongDethis");

                    b.Navigation("DDethis");

                    b.Navigation("Dapans");

                    b.Navigation("Lichsuduyetches");

                    b.Navigation("Phanloaiches");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Dangkythithu", b =>
                {
                    b.Navigation("Bienbanthithus");

                    b.Navigation("Diemthis");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Dethi", b =>
                {
                    b.Navigation("DDethis");

                    b.Navigation("Dangkythithus");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Dethidatao", b =>
                {
                    b.Navigation("CauhoitrongDethis");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Diendan", b =>
                {
                    b.Navigation("Baiviets");

                    b.Navigation("GiaovienDiendans");

                    b.Navigation("Thamgia");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Dondenghitaodd", b =>
                {
                    b.Navigation("Diendans");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Giaovien", b =>
                {
                    b.Navigation("Baiviets");

                    b.Navigation("Cauhois");

                    b.Navigation("Dethidataos");

                    b.Navigation("GiaovienDiendans");

                    b.Navigation("Lops");

                    b.Navigation("Nhomches");

                    b.Navigation("Tailieuhoctaps");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Kiemduyetvien", b =>
                {
                    b.Navigation("Cauhois");

                    b.Navigation("Lichsuduyetches");

                    b.Navigation("Lichsuduyettls");

                    b.Navigation("Tailieuhoctaps");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Kynang", b =>
                {
                    b.Navigation("Phanloaiches");

                    b.Navigation("Phanloaitls");

                    b.Navigation("Phanthis");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Lichsuduyettl", b =>
                {
                    b.Navigation("Dangkythithus");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Loaidethi", b =>
                {
                    b.Navigation("Dethidataos");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Loaitailieu", b =>
                {
                    b.Navigation("Tailieuhoctaps");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Lop", b =>
                {
                    b.Navigation("Dangkyonluyens");

                    b.Navigation("Thongkelops");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Mucdokho", b =>
                {
                    b.Navigation("Cautrucdethis");

                    b.Navigation("Phanloaiches");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Nhomch", b =>
                {
                    b.Navigation("Cauhois");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Phanthi", b =>
                {
                    b.Navigation("Cautrucdethis");

                    b.Navigation("Nhomches");

                    b.Navigation("Phanloaiches");

                    b.Navigation("Phanloaitl");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Phieubaitaponluyen", b =>
                {
                    b.Navigation("Cauhoibaitaps");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Sinhvien", b =>
                {
                    b.Navigation("Chitietbaithis");

                    b.Navigation("Dangkyonluyens");

                    b.Navigation("Dangkythithus");

                    b.Navigation("Dethidataos");

                    b.Navigation("Diemthis");

                    b.Navigation("Donkhieunais");

                    b.Navigation("Phieubaitaponluyens");

                    b.Navigation("Thamgia");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Tailieuhoctap", b =>
                {
                    b.Navigation("Lichsuduyettls");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Trangthaich", b =>
                {
                    b.Navigation("Cauhois");

                    b.Navigation("LichsuduyetchMaTtSauNavigations");

                    b.Navigation("LichsuduyetchMaTtTruocNavigations");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Trangthaidethi", b =>
                {
                    b.Navigation("Dethidataos");
                });

            modelBuilder.Entity("ToeicCentre_Management.Models.Trangthaitl", b =>
                {
                    b.Navigation("LichsuduyettlMaTtMoiTlNavigations");

                    b.Navigation("LichsuduyettlMaTtTruocTlNavigations");

                    b.Navigation("Tailieuhoctaps");
                });
#pragma warning restore 612, 618
        }
    }
}
